geeksforsocialchange/PlaceCal

README.md
=> Changed software requirements for installing PlaceCal.

app/controllers/admin/calendars_controller.rb, app/controllers/admin/partners_controller.rb, app/models/calendar.rb, app/models/calendar_parser.rb, app/models/event.rb, app/models/parsers/base.rb, app/models/parsers/facebook.rb, app/models/parsers/ics.rb, app/models/parsers/manchester_uni.rb, app/models/parsers/xml.rb, app/models/parsers/zarts.rb, app/views/admin/calendars/_form.html.erb, app/views/events/show.html.erb, db/migrate/20180720112624_add_critical_error_to_calendar.rb, db/schema.rb, lib/tasks/events.rake
fix type and place calend columns
add comment to parsers
=> add critical error field and store import failures

app/controllers/partners_controller.rb, app/controllers/places_controller.rb, test/controllers/partners_controller_test.rb, test/controllers/places_controller_test.rb
Implemented through a literal SQL join. I assume this is the
least maintainable way to do it. It works for now.
=> Added filtering of partners and places for subsites.

app/controllers/application_controller.rb
=> Removed mention of non-existent class Place

app/models/calendar.rb, app/models/events/base.rb, app/models/parsers/ics.rb
add proudtrust to ics whitelist
=> replace invalid characters in summary and description

.travis.yml, INSTALL.md, README.md, app/components/footer/_footer.html.erb, app/components/footer_home/_footer_home.html.erb, doc/file.INSTALL.html, doc/file.README.html, doc/index.html, scripts/production.sh, scripts/staging.sh
Change references from 'master' to 'main' in documentation and templated html pages
=> Change references from 'master' to 'main'

Gemfile, Gemfile.lock, babel.config.js, package.json, yarn.lock
Update bundle, yarn dependencies. In practice this covers all of the stuff that dependabot suggested.
=> Silence, dependabot!

test/policies/partner_policy_test.rb
Via suggestion from @kimadactyl
=> Skip failing test (Temporarily fixes #785)

config/environments/production.rb, config/environments/staging.rb
=> Switch to using SMTP gateway to Mailersend

Gemfile, Gemfile.lock, babel.config.js, yarn.lock
Pinned webpacker since the new release will cause difficulty with heroku buildpacks AFAIK
=> Updated some dependencies.

db/migrate/20211203153422_correct_datamodel_by_importing_neighbourhoods_json.rb, db/migrate/20220105161548_fix_broken_datamodel.rb, db/schema.rb, yarn.lock
Repair broken data migration / find-placecal endpoint broken (Fixes #874).
Update yarn lockfile.
=> Repair broken data migration / find-placecal endpoint broken

app/controllers/admin/calendars_controller.rb, app/controllers/admin/collections_controller.rb, app/controllers/admin/neighbourhoods_controller.rb, app/controllers/admin/sites_controller.rb, app/controllers/admin/supporters_controller.rb, app/controllers/admin/tags_controller.rb, app/controllers/admin/users_controller.rb
=> Improve admin UI flash messages

app/helpers/users_helper.rb
In admin users edit page. Implements #909
=> Use of contextual_name in neighbourhoods selector

app/datatables/partner_datatable.rb, app/models/partner.rb, test/models/partner_test.rb
- Fix Partners Search (No AJAX Error)
- Fix (And Test For) Partner Validation Error (No Weirdness!)
=> Partners hotfixes: datatable search & summary and description visibility methods

Gemfile, Gemfile.lock, app/assets/config/manifest.js, app/controllers/graphql_controller.rb, app/graphql/mutations/base_mutation.rb, app/graphql/place_cal_schema.rb, app/graphql/types/base_argument.rb, app/graphql/types/base_connection.rb, app/graphql/types/base_edge.rb, app/graphql/types/base_enum.rb, app/graphql/types/base_field.rb, app/graphql/types/base_input_object.rb, app/graphql/types/base_interface.rb, app/graphql/types/base_object.rb, app/graphql/types/base_scalar.rb, app/graphql/types/base_union.rb, app/graphql/types/mutation_type.rb, app/graphql/types/node_type.rb, app/graphql/types/query_type.rb, app/views/layouts/application.html.erb, config/routes.rb
(Implements #918)
See config/routes.rb for access points
You can access it by localhost:3000/graphiql
=> Base GraphQL library and mount-points

app/graphql/place_cal_schema.rb, app/graphql/types/partner_type.rb, app/graphql/types/query_type.rb, test/integration/graphql/partners_integration_test.rb, test/integration/graphql/ping_integration_test.rb
=> Graphql partner endpoints

app/views/admin/users/edit.html.erb
=> Admin users must confirm user delete

config/locales/devise_invitable.en.yml
=> Tweak Invite User email text

app/components/place_partner_preview/_place_partner_preview.html.erb
=> Remove partner summary truncation

app/helpers/partners_helper.rb, app/models/partner.rb, app/views/admin/partners/edit.html.erb, test/controllers/partners_controller_test.rb, test/models/partner_test.rb
=> Ik 984 partner address service area validation v2

app/controllers/admin/partners_controller.rb, app/models/partner.rb, app/models/user.rb, test/models/partner_test.rb
Implements #988 
Business logic should be complete and ready for optimisation
=> Partners now validate service areas for users

app/graphql/types/neighbourhood_type.rb, app/graphql/types/query_type.rb, app/graphql/types/site_type.rb, test/integration/graphql/site_integration_test.rb
Implements #992 by adding sites to the gql interface (with tests).
Also an attempt to separate the query code into modules of concerns
=> Graphql sites API endpoints

config/initializers/rollbar.rb
Fixes #1023, hopefully. However there's no way to actually test this until it deploys
=> Fix rollbar logging

app/views/admin/users/new.html.erb, test/integration/admin/user_integration_test.rb
Fix for bug where admin user form was forced to be an update and not a create action
=> Fix admin user form

app/graphql/types/contact_info_type.rb, app/graphql/types/partner_type.rb, test/integration/graphql/partners_integration_test.rb
So you can do:
query {
allPartners {
id
name
description
contactInfo {
name
phone
email
}
}
}
=> GraphQL Partner public contact info data fields

app/graphql/place_cal_schema.rb, app/graphql/types/query_type.rb, test/integration/graphql/event_integration_test.rb, test/integration/graphql/partners_integration_test.rb, test/integration/graphql/site_integration_test.rb
Implements #1034 - API pagination on Events, Partners and Sites
=> API pagination

app/graphql/types/address_type.rb, app/graphql/types/contact_type.rb, app/graphql/types/neighbourhood_type.rb, app/graphql/types/opening_hours_type.rb, app/graphql/types/partner_type.rb, config/routes.rb, doc/adr/0008-partner-graphql-schema.md, test/integration/graphql/event_integration_test.rb, test/integration/graphql/partners_integration_test.rb
Implements #1040 
Improves schema for partners and adds versioning to API endpoint
=> Partner schema enhancement

app/helpers/sites_helper.rb, app/javascript/src/behaviors/behaviors.partner.js, app/javascript/src/behaviors/behaviors.site.js, app/models/site.rb, app/models/sites_tag.rb, app/models/tag.rb, app/policies/site_policy.rb, app/views/admin/partners/_form.html.erb, app/views/admin/sites/_form.html.erb, db/migrate/20220310125155_add_sites_tags.rb, db/schema.rb, test/integration/admin/partner_integration_test.rb, test/integration/admin/sites_integration_test.rb
- Add SitesTags Join
- Add Site Tags to view
- Fix multiple select problem
- Move Partners Tags edit to select2
- Fixup tests
Fixes #1046 
Partial fix of #1029
=> Add SitesTags. Add Site Tags to view, tests. Fix multiple select problem

app/graphql/types/event_type.rb, app/graphql/types/query_type.rb, config/routes.rb, test/integration/graphql/event_integration_test.rb
=> New response format for Events via graph api

app/components/place_partner_preview/place_partner_preview_component.rb, app/controllers/sites_controller.rb, app/models/partner.rb, app/views/admin/sites/_form.html.erb, test/integration/partners_integration_test.rb
=> Add site tag filtering; add test for site tag filtering

app/graphql/types/article_type.rb, app/graphql/types/event_queries.rb, app/graphql/types/event_type.rb, app/graphql/types/partner_type.rb, app/models/article.rb, test/integration/graphql/event_integration_test.rb, test/integration/graphql/partners_integration_test.rb
=> Articles can be accessed through partner API

app/graphql/types/partner_type.rb, app/graphql/types/query_type.rb, app/models/partner.rb, test/integration/graphql/partners_integration_test.rb
Implements #1070 
Tidies up code a small bit
=> GraphQL refactor

app/components/admin_edit/_admin_edit.html.erb, app/components/admin_index/_admin_index.html.erb, app/views/admin/articles/new.html.erb, app/views/admin/calendars/new.html.erb, app/views/admin/pages/home.html.erb, app/views/admin/partners/edit.html.erb, app/views/admin/partners/new.html.erb, app/views/admin/sites/new.html.erb, app/views/admin/tags/new.html.erb, app/views/admin/users/new.html.erb, app/views/layouts/_meta.html.erb, app/views/layouts/admin/_datatable.html.erb, app/views/layouts/admin/application.html.erb, app/views/layouts/application.html.erb, test/integration/admin/calendars_integration_test.rb, test/integration/admin/home_integration_test.rb, test/integration/admin/neighbourhood_integration_test.rb, test/integration/admin/partner_integration_test.rb, test/integration/admin/sites_integration_test.rb, test/integration/admin/user_integration_test.rb
=> Add titles to admin pages

app/controllers/application_controller.rb, app/models/event.rb, test/integration/event_site_integration_test.rb
Implements #1068 Sites with tags filter their events for partners with the same tag
=> Events are filtered by site tag

app/graphql/types/query_type.rb, test/integration/graphql/partners_integration_test.rb
=> Find partners by tag

app/graphql/types/neighbourhood_type.rb, app/models/address.rb, app/models/neighbourhood.rb, db/migrate/20220329140520_fix_address_and_neighbourhood_fields.rb, db/schema.rb, test/models/address_test.rb, test/models/neighbourhoods_test.rb
Fixes #1079
There is a migration that must run on data in db.
=> Clean up postcodes with excess whitespace

app/models/calendar.rb, app/models/event.rb, test/models/events_test.rb
Kinda Fixes #1072 
Also has our first yarddoc comment :partying_face:
=> Remove event duplicates where dtstart, summary, and calendar_id are the same

app/graphql/types/partner_type.rb, test/integration/graphql/partners_integration_test.rb
=> Safely read opening_times from partner

app/graphql/types/query_type.rb, app/models/article.rb, test/integration/graphql/article_by_tag_query_test.rb, test/integration/graphql/articles_by_partner_tag_test.rb, test/models/article_test.rb
Implements part of the articles by tag id filter
=> Filter articles by tagID graphql endpoint

app/views/admin/articles/edit.html.erb
=> Title on admin edit article page

package.json
=> Change yarn and node version

config/environments/production.rb, config/environments/staging.rb
- Fix Uglifier issue
- Also compress js on production
=> Fix Uglifier issue during deploy

app/controllers/admin/articles_controller.rb, app/controllers/admin/calendars_controller.rb, app/controllers/admin/collections_controller.rb, app/controllers/admin/neighbourhoods_controller.rb, app/controllers/admin/omniauth_callbacks_controller.rb, app/controllers/admin/partners_controller.rb, app/controllers/admin/sites_controller.rb, app/controllers/admin/supporters_controller.rb, app/controllers/admin/tags_controller.rb, app/controllers/admin/users_controller.rb
=> Add HTTP 422 to render errors

app/jobs/calendar_importer/calendar_importer.rb, app/jobs/calendar_importer/calendar_importer_task.rb, app/jobs/calendar_importer/event_resolver.rb, app/jobs/calendar_importer/events/base.rb, app/jobs/calendar_importer/events/eventbrite_event.rb, app/jobs/calendar_importer/events/facebook_event.rb, app/jobs/calendar_importer/events/ics_event.rb, app/jobs/calendar_importer/events/manchester_uni_event.rb, app/jobs/calendar_importer/events/meetup_event.rb, app/jobs/calendar_importer/events/zarts_event.rb, app/jobs/calendar_importer/parsers/base.rb, app/jobs/calendar_importer/parsers/eventbrite.rb, app/jobs/calendar_importer/parsers/facebook.rb, app/jobs/calendar_importer/parsers/ics.rb, app/jobs/calendar_importer/parsers/manchester_uni.rb, app/jobs/calendar_importer/parsers/meetup.rb, app/jobs/calendar_importer/parsers/xml.rb, app/jobs/calendar_importer/parsers/zarts.rb, app/jobs/calendar_importer_job.rb, app/models/address.rb, app/models/calendar.rb, app/models/partner.rb, lib/tasks/events.rake, test/jobs/calendar_importer/calendar_importer_test.rb, test/jobs/calendar_importer/events_import_test.rb
=> Refactor calendar importer

app/jobs/calendar_importer/calendar_importer_task.rb
=> Events with no locations are valid now

app/datatables/calendar_datatable.rb, app/views/admin/calendars/index.html.erb
=> Fixup datatables on Calendar page

app/helpers/calendars_helper.rb, app/jobs/calendar_importer/calendar_importer.rb, app/jobs/calendar_importer/events/ticketsolve_event.rb, app/jobs/calendar_importer/parsers/base.rb, app/jobs/calendar_importer/parsers/eventbrite.rb, app/jobs/calendar_importer/parsers/facebook.rb, app/jobs/calendar_importer/parsers/ics.rb, app/jobs/calendar_importer/parsers/manchester_uni.rb, app/jobs/calendar_importer/parsers/meetup.rb, app/jobs/calendar_importer/parsers/ticketsolve.rb, app/jobs/calendar_importer/parsers/zarts.rb, app/views/admin/calendars/_form.html.erb
=> Admin calendar url hints

app/components/map/_map.html.erb, app/controllers/application_controller.rb
Fixes 1105 - Only partners without service areas show up on the map
=> Partners with service areas don't show up on the map

app/components/place_partner_preview/place_partner_preview_component.rb, app/controllers/events_controller.rb, app/graphql/types/event_queries.rb, app/jobs/calendar_importer/event_resolver.rb, app/jobs/calendar_importer/parsers/base.rb, app/jobs/calendar_importer/parsers/ics.rb, app/models/event.rb, app/views/admin/partners/edit.html.erb, app/views/partners/index.html.erb, test/factories/event.rb, test/models/events_test.rb
=> Assign partners to events when imported

app/components/event/event_component.rb, app/jobs/calendar_importer/event_resolver.rb, config/database.yml
Events longer than 1 day are now imported and the duration display adjusts accordingly
=> Multi day events

app/jobs/calendar_importer/event_resolver.rb, app/models/address.rb, lib/tasks/events.rake
- Drastically simplified `place` strategy
- Removed some unnecessary nesting to (hopefully?) make it clearer to
reason about
- Explicitly document race conditions in comments
- Make sure that events_from_source passes force_import (we can't
actually let the user set this because rake argument passing isn't
nice about this)
=> Make Calendar code slightly clearer

app/helpers/calendars_helper.rb, app/jobs/calendar_importer/event_resolver.rb, app/models/calendar.rb, app/models/event.rb, test/controllers/events_controller_test.rb, test/controllers/partners_controller_test.rb, test/jobs/calendar_importer/event_resolver_test.rb
=> Add a "no location" strategy to Calendars

app/jobs/calendar_importer_job.rb, app/models/calendar.rb, test/models/calendar_test.rb
=> Calendar notice count

app/controllers/application_controller.rb, app/models/event.rb, test/models/events_test.rb
=> Remove DATE() from find_by_day

app/jobs/calendar_importer/calendar_importer_task.rb, app/jobs/calendar_importer/events/base.rb, app/jobs/calendar_importer/events/ics_event.rb, lib/tasks/events.rake
=> Sanitise and combine strings on iCal event description fields

Procfile.dev, app/controllers/admin/jobs_controller.rb, app/views/admin/jobs/index.html.erb, app/views/layouts/admin/_admin_navigation.html.erb, config/routes.rb, lib/tasks/events.rake
=> Migrate to delayed_job and add ActiveJob worker

app/helpers/calendars_helper.rb, app/jobs/calendar_importer/calendar_importer.rb, app/jobs/calendar_importer/calendar_importer_task.rb, app/jobs/calendar_importer/parsers/base.rb, app/jobs/calendar_importer/parsers/eventbrite.rb, app/jobs/calendar_importer/parsers/facebook.rb, app/jobs/calendar_importer/parsers/ics.rb, app/jobs/calendar_importer/parsers/meetup.rb, app/jobs/calendar_importer/parsers/ticketsolve.rb, app/models/calendar.rb, app/views/admin/calendars/_form.html.erb, db/migrate/20220516083725_add_importer_mode_to_calendar.rb, db/schema.rb, test/fixtures/vcr_cassettes/Uknown_Teamup_Feed.yml, test/jobs/calendar_importer/calendar_importer_task_test.rb, test/jobs/calendar_importer/calendar_importer_test.rb, test/models/calendar_state_test.rb
=> Manual importer selection

app/controllers/admin/calendars_controller.rb, test/integration/admin/calendars_integration_test.rb
A small oversight implementing front end logic supporting calendar configuration
=> Saving calendar import mode on admin page

app/models/partner.rb, test/controllers/admin/partners_controller_test.rb, test/controllers/partners_controller_test.rb, test/factories/event.rb
- fix: users unable to edit partner without shared ward
- refactor: parts of controller test for ease of reading
- fix: event factories sequential summary generation
=> Fix bug where users were unable to edit a partner without a common ward

app/jobs/calendar_importer/calendar_importer_task.rb, app/jobs/calendar_importer/event_resolver.rb, app/jobs/calendar_importer/parsers/ics.rb, app/jobs/calendar_importer_job.rb, app/models/calendar.rb, lib/tasks/events.rake
Fixes #1261 - calendar importer not changing state correctly if an import has no events
=> Importer not logging importer used

app/helpers/application_helper.rb, app/jobs/calendar_importer/events/base.rb, app/models/article.rb, app/models/concerns/html_render_cache.rb, app/models/event.rb, app/models/partner.rb, app/models/site.rb, app/views/events/show.html.erb, app/views/news/index.html.erb, app/views/news/show.html.erb, app/views/partners/show.html.erb, app/views/sites/default.html.erb, app/views/sites/mossley.html.erb, db/migrate/20220611154511_add_html_fields_to_models.rb, db/schema.rb, lib/tasks/data.rake, test/jobs/calendar_importer/event_base_html_sanitize_test.rb, test/models/article_test.rb
=> Remove HTML from imported events

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/invitation_instructions.text.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb
=> Improve invite email

lib/tasks/data.rake
Was not performing well in production environment
=> Fix data migration

app/components/paginator/_paginator.html.erb, app/components/paginator/paginator_component.rb, app/controllers/partners_controller.rb, app/views/partners/show.html.erb, db/schema.rb, test/integration/partner_integration_test.rb
=> Improve event display when there are limited events

app/assets/stylesheets/base/flash.sass, app/assets/stylesheets/globals.sass
Fixes #1314. Move out of Mountain View into app assets dir
=> bug: root domain flash styling fix

app/controllers/users/invitations_controller.rb, app/views/devise/invitations/edit.html.erb
=> Fix accept invitation form and redirect

app/helpers/application_helper.rb, app/views/layouts/admin/_admin_navigation.html.erb
=> Only show certain nav links to certain admins

app/assets/stylesheets/articles/_index.sass, app/assets/stylesheets/articles/_show.sass, app/controllers/application_controller.rb, app/helpers/articles_helper.rb, app/models/article.rb, app/views/news/index.html.erb, app/views/news/show.html.erb, test/integration/news_integration_test.rb
Fixes #1324 
But needs layout and styling for the new fields
=> News items bugs

app/assets/stylesheets/articles/_index.sass, app/assets/stylesheets/articles/_show.sass, app/views/news/show.html.erb
Is now more inline with the show partner/event
Implements #1330
=> Show article page layout and styling

.gitignore, app/views/admin/partners/edit.html.erb
=> Change of text on admin edit partner page.

app/views/joins/new.html.erb
=> Text and formatting change

app/jobs/calendar_importer_job.rb
=> Don't update calendars timestamp when saving

app/views/admin/pages/home.html.erb, test/integration/admin/home_integration_test.rb
=> No rights for user message on admin dashboard

app/helpers/users_helper.rb, test/integration/admin/home_integration_test.rb
Fixes problem with original PR
=> fix: Root users incorrectly getting warning they have no rights

.github/workflows/test.yml, README.md, app/assets/stylesheets/application.sass, app/views/devise/invitations/edit.html.erb, package.json, test/application_system_test_case.rb, test/system/application_system_test_case.rb, test/system/collections_test.rb, test/system/create_admin_users_test.rb, test/system_test_helper.rb, test/test_helper.rb, yarn.lock
Is solving #870 where we use browser testing to verify the front end is running. So far only the system test framework has been set up and an example test has been written. Later tests will deal specifically with the javascript components.
=> System tests

app/controllers/users/auth_common.rb, app/controllers/users/invitations_controller.rb, app/controllers/users/sessions_controller.rb, app/views/admin/users/profile.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/unlocks/new.html.erb, test/integration/devise_redirection_test.rb, test/integration/users_log_in_go_to_admin_site_test.rb, test/support/email_helper.rb, test/test_helper.rb
Fixes #1327 - send users to correct domains
=> Devise password redirects

app/models/calendar.rb, test/models/calendar_state_test.rb
Hopefully Fixes #1329 
Calendar objects are reloaded before flagging for error (discarding any
invalid state that may have built up).
+ tests covering this
=> Fix calendar importer tasks stuck in "in worker" mode

app/views/admin/sites/_form.html.erb
=> Site admin contact selector has a search filter

app/components/event/event_component.rb, app/models/event.rb, test/controllers/events_controller_test.rb, test/integration/event_site_integration_test.rb, test/models/events_test.rb
Fixes #1214
Wasn't sure who specifically to assign to review so - you get assigned, and you get assigned, and you ALL get assigned
=> Make multi-day events show properly in interface (#1214)

app/models/partner.rb, test/integration/partners_integration_test.rb, test/models/partner_site_scope_test.rb
=> Fix duplicate partners on partner index pages

app/models/partner.rb, test/integration/partners_integration_test.rb, test/models/partner_site_scope_test.rb
This reverts commit a1aadba95fffd5d6d0b6e1d9002a2914edf19497.
=> Revert "Fix duplicate partners on partner index pages (#1432)"

README.md
=> Document Graphviz dependency

.env.example, app/graphql/types/partner_type.rb, app/models/partner.rb, app/uploaders/image_uploader.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb
=> Fix: set up domain and build partner logo url

app/jobs/calendar_importer/parsers/base.rb, app/jobs/calendar_importer/parsers/meetup.rb, test/fixtures/vcr_cassettes/bad_meetup_gateway.yml, test/jobs/calendar_importer/meetup_parser_test.rb, test/jobs/calendar_importer/parser_base_test.rb
=> Fix: make importer JSON parsing more robust

Gemfile, Gemfile.lock, app/jobs/calendar_importer/events/base.rb, app/models/address.rb, app/validators/postcode_validator.rb, test/models/address_test.rb
Rather than maintaining a giant regular expression, let's lean on prior art, maintained by someone else.
Fixes #1483
=> Use uk_postcode gem for postcode validation

.github/workflows/deploy-to-production.yml, .github/workflows/deploy-to-staging.yml, .github/workflows/test.yml
Hopefully this fixes deployments.
=> Release a hotfix for the deployment to production

app/jobs/calendar_importer/events/out_savvy_event.rb
Fixes #1531 
- Event
- VisualArtsEvent
- SocialEvent
- DanceEvent
=> Fix OutSavvy importer failing due to multiple event types specified in metadata

app/helpers/events_helper.rb, app/views/events/show.html.erb, test/controllers/events_controller_test.rb
=> remove markdown from metadata descriptions

renovate.json
=> Improve renovate

app/controllers/admin/jobs_controller.rb, app/views/admin/jobs/_calendar_row.html.erb, app/views/admin/jobs/index.html.erb
=> More information shown on admin jobs page

app/models/partner.rb, test/models/partner_test.rb
Fixes #1663 
Not just on create
=> Validate partner service areas / addresses on save

app/models/partnership.rb, app/policies/partnership_policy.rb, app/views/admin/tags/_form.html.erb
=> Partnership tag type

app/controllers/application_controller.rb, app/views/layouts/admin/_admin_navigation.html.erb, test/integration/news_integration_test.rb
=> Remove News link, rehome admin Articles nav

app/components/address/address_component.rb, app/views/events/show.html.erb
=> Show raw location on Events if no Address present

app/helpers/partners_helper.rb, app/models/address.rb, app/models/neighbourhood.rb, app/views/admin/partners/_form.html.erb, test/models/address_test.rb
Fixes #1808 
Sort of. Changes feedback message
=> Changed text of address postcode validation

Gemfile, Gemfile.lock, test/test_helper.rb
=> Database cleaner

app/components/home_strapline_component/home_strapline_component.html.erb, app/components/neighbourhood_home_card_component/neighbourhood_home_card_component.html.erb, app/views/pages/find_placecal.html.erb, app/views/pages/home.html.erb
fixes #1858 
I'm a bit weary of this issue because I think it might make extra work if something existing can be approved we won't have to undo it. 
That being said - here it is. I hope it's useful.
=> add [cCc] to filler content

app/components/full_width_action_component/full_width_action_component.html.erb, app/components/full_width_action_component/full_width_action_component.scss, app/components/home_strapline_component/home_strapline_component.html.erb, app/components/home_strapline_component/home_strapline_component.sass, app/components/max_width_component.rb, app/components/max_width_component/max_width_component.html.erb, app/components/max_width_component/max_width_component.scss, app/views/pages/home.html.erb
fixes #1859 
- created a wrapper component to we can use when building other components, this should help us keep consistent and allow us to make changes across the system if needed.
- I've applied it to the block quote even though it's not a new component, this makes the text line up better but makes the quote marks a little odd. I'm happy to remove at reviewers request!
=> contstrain text width on homepage

app/components/footer/_footer.html.erb, app/views/joins/new.html.erb
Fixes #1872 
Removes all occurrences of the phone number from the site
=> Remove phone number from site

app/views/pages/home.html.erb
Fixes #1843
Content for big blocks
=> update block text

app/components/home_footer_component/home_footer_component.html.erb
Fixes #1882 
- Makes email addresses the same in the footer & get in touch form on the home site
=> Make emails the same

app/components/neighbourhood_home_card_component/neighbourhood_home_card_component.scss, app/components/partnership_card_component/partnership_card_component.scss
fixes #1887 
Improves the appearance of neighbourhood & partnership cards & buttons
=> improve button appearance

app/components/full_width_action_component/full_width_action_component.scss
Fixes #1893 
Font size increased by 0.3 rem
=> Increase font size on action boxes

app/components/partnership_card_component.rb
Fixes #1892
Fixes faulty image urls
=> update image address

lib/tasks/db.rake
=> Make rails db:db:sync_prod_staging work

app/components/hero_image_component.rb, app/models/site.rb, app/policies/site_policy.rb, app/views/admin/sites/_form.html.erb, app/views/sites/default.html.erb, db/migrate/20230724125445_add_hero_text_to_site.rb, db/schema.rb, test/integration/sites_integration_test.rb
fixes #1983 
- add `hero_text` to `Site` model
- limit length to 120 chars
- conditionally display custom text, the component already falls back to "PlaceCal is a community events calendar where you can find everything near you, all in one place."
=> custom banner text

app/views/pages/privacy.html.erb
=> Made privacy policy more visible

app/views/admin/pages/home.html.erb
Fixes #1964 #1335 
The simplest solution is to remove the slow queries. Have added a comment to the originating issue covering why it is slow and a few notes on how it could be optimised further.
=> Speed up slow loading of admin dashboard

app/views/layouts/admin/_admin_topbar.html.erb
=> removed unused search bar from admin area

.github/ISSUE_TEMPLATE/new_site.md
=> Add template for a new site to be created

app/views/admin/partners/_form.html.erb
=> Changed warning text on partner address form

app/views/admin/jobs/index.html.erb
Closes #2070
Importer status table has actual counts in it
=> Admin jobs page

app/models/calendar.rb, test/fixtures/vcr_cassettes/unsupported_url.yml, test/models/calendar_test.rb
Closes #1985 
Better help text when the user enters an unknown URL as the calendar source.
=> Better feedback on calendars with a source

app/components/event/event_component.rb
=> Don't try to read event end date when it is not set

config/initializers/rollbar.rb, lib/rollbar_exception_filter.rb, test/lib/rollbar_exeption_filter_test.rb
Fixes #2126 
Stop rails from logging really common routing errors to rollbar
=> Rollbar exception filter

app/views/admin/partners/_form.html.erb, app/views/admin/partners/edit.html.erb, test/integration/admin/partner_integration_test.rb, test/system/admin/partner_test.rb
Fixes #2140 
Fixes #2139 
- It looks like a bit of form crept back in as a repeat which broke the select-2 controller because it now had two multiple choices referencing it on the same page
- The section below the form was not being included in the main tag when the page renders. I have no idea why this is so for now I have simply added a container to ensure the styling is correct and will add this as a different issue
- I've uncommented the broken tests - hopefully this is why they broke 🤞
=> Fix UI regressions

Gemfile, Gemfile.lock, app/assets/config/manifest.js, config/environments/test.rb, config/schedule.rb, test/test_helper.rb
Reverts geeksforsocialchange/PlaceCal#2181
Reason: there is a problem with the CI server and the earlier ruby update PR #2156
=> Revert "Nuking gems"

Gemfile, Gemfile.lock, app/assets/config/manifest.js
To fix CI build problem.
Also fixing missing test assets
=> Added gems to gemfile

Gemfile, Gemfile.lock
TODO: find out where this is coming from
=> Putting back coffeescript so staging will be happy

app/views/admin/users/edit.html.erb
=> dont show useless delete button

app/policies/user_policy.rb, test/controllers/admin/users_controller_test.rb
see #2054
fixes #2104
Nice to delete that conditional, something like that always gives me a bad feeling. Also removed a contradictory test, not sure how that and the test below it were both passing. I guess the problem with having tests for a refactor is that when you change how the system works a passing test is no longer an indication of desired behavior.
=> only root users can delete users

app/controllers/admin/partners_controller.rb, app/controllers/admin/users_controller.rb
fixes #2211 
fixes #2216
turns out it was a very simple fix :confetti_ball:  that required a lot of digging :hole:
=> fix: broken select2 imputs when form validation fails

app/helpers/application_helper.rb, test/controllers/concerns/tag_filter_test.rb, test/jobs/calendar_importer/eventbrite_parser_test.rb, test/jobs/calendar_importer/ld_json_parser_test.rb, test/jobs/calendar_importer/parser_base_test.rb, test/test_helper.rb
Small changes that should allow #2164, #2166, and #2167 to merge
=> Make changes requested by rubocop upgrades to allow renovate PRs to merge

app/helpers/partners_helper.rb, app/views/admin/partners/edit.html.erb
Closes #2231 
This is just a list of links to the sites (as the original behaviour) not links to the partner page of that site.
=> Show admins the sites this partner appears on

lib/tasks/db.rake
=> fix: make setup_with_docker

app/models/calendar.rb, test/models/calendar_test.rb
=> Calendars clear importer problems on source value change

app/jobs/calendar_importer/parsers/ics.rb, test/fixtures/vcr_cassettes/Martin_Harris_Centre.yml
Closes #2409 
- Specific client in calendar ICS parser
- Personal email address from VCR cassette
=> Removing live data from code

app/models/event.rb
=> Fixes minor scoping bug on `Event.for_site`

app/views/admin/calendars/_form.html.erb, app/views/admin/calendars/_importer_overview.html.erb
Closes #2429 
Even if calendar has not been successfully imported
=> Show import status on admin calendar form at all times

app/helpers/calendars_helper.rb, app/models/calendar.rb, app/views/admin/calendars/_form.html.erb
Fixes #2403 
Improves the copy & layout of the location information on the calendar importer so that it is easier for users to understand.
=> Improve importer UI and copy

app/helpers/events_helper.rb
=> Made online link copy more accurate

app/views/admin/partners/edit.html.erb
Fixes #2364
I've tried to rewrite this as simply as possible to make it easier to understand what could be wrong from a glance - the previous message felt very long. Happy to can this if people think it's not an improvement.
I haven't touched the partner hidden thing - we're just opening a new ticket for that as a separate issue instead, because it needs some design thinking.
=> Simplify error text

app/views/admin/partners/_form.html.erb, app/views/admin/partners/new.html.erb
=> Microcopy changes for tags

.gitignore, app/assets/stylesheets/base/icon-font.scss, app/assets/stylesheets/globals.scss, app/components/event/_event.html.erb, app/components/home_footer_component/home_footer_component.html.erb, app/controllers/events_controller.rb
- [Remove scrambled `<p>` tag](https://github.com/geeksforsocialchange/PlaceCal/pull/2414#issuecomment-2186880129)
- [Fix icon font](https://github.com/geeksforsocialchange/PlaceCal/pull/2485#issuecomment-2186890635)
- [Reduce weekly view limit to 50](https://github.com/geeksforsocialchange/PlaceCal/pull/2473#issuecomment-2188396964)
=> Fix errors raised in release validation

app/controllers/pages_controller.rb, app/controllers/sites_controller.rb, app/models/site.rb, config/robots/robots.development.txt, config/robots/robots.staging.txt, config/robots/robots.test.txt, test/integration/robots_integration_test.rb
=> feat: Unpublished sites are hidden from search engines

README.md, app.json
Oops, forgot cron is set in the dokku config
=> fix: update cron command

app/views/admin/calendars/_form.html.erb
Oops, something went awry here
Fixes #2536
=> fix: Handbook URL ref

config/routes.rb
@katjam - if you want a GET endpoint this is all we need to do. feel free to merge it yourself if you want to experiment on staging. the bruno collections just work if i switch to GET! feels too easy...
=> feat: Add GET endpoint to GraphQL API

.github/workflows/test-and-deploy.yml
Unclear why or how it was working without this in there but all CI tests failing atm due to this!
=> fix: add imagemagick to ci script

.github/workflows/test-and-deploy.yml
This is a temporary bandage on #2704 to try and help getting some improvements moving along. Needs to be revisited and does not resolve.
-->
Resolves # 
Stops the system tests being run as they're incredibly flaking and preventing other work being merged.
=> fix: temporary fix on tests failing

app/jobs/calendar_importer/parsers/ld_json.rb
Resolves #2762
Fixed typo in `EventConsumer` causing error.
=> fix: Typo in EventConsumer

app/models/site.rb, db/seeds/004_sites.rb
Resolves #2796 
Removes strict HTTPS URL validation on the sites model so that HTTP URLs are usable during local development
Adds a demo site and country so that something gets published on initial launch, making the onboarding process much nicer for new developers
This is a big improvement to the onboarding process of new developers, making a new installation of Placecal launch with enough example data to be usable
In Alice's Docker development environment
In development environment this gets deployed with `./bin/setup`. I don't know what implications these seeds have for production
=> fix(models): remove https-only URL validation and add example site
