geeksforsocialchange/PlaceCal

- app/components/event/_event.html.erb
- app/components/event/event.yml
- app/components/event/event_component.rb
- app/models/event.rb
Removed Event#location.
* The only place it was called from was the EventComponent UI class.
* Changed EventComponent to use Event#address directly.
> Killed redundant and confusing Event#location

- app/controllers/application_controller.rb
- app/controllers/partners_controller.rb
- config/routes.rb
- test/controllers/partners_controller_test.rb
Removed all place / partner distinction. All Partners in the relevant geographical region are shown on the partners page.
> Removed places index. Only one Partner index now.

- app.json
Dokku has the ability to have it's own crontab thing in the `app.json` for actions that are intended to be run using `dokku enter`, since both production and staging have a crontab that has the `import:all_events` action running every ten minutes it's probably better to just stick it into the `app.json` and then any changes we need to make (none, but...) will just automagically sync across production and staging, it's also a 2 second conversion anyway since it's just commenting out the old crontab and adding like 2 or 3 lines to the `app.json` (as you can see here! haha)
it's a 1-1 conversion so there's almost no chance of it actually going wrong, I switched it to using `bundle exec rails import:all_events` because that seemed the most correct modification to it, those should be …
> Switch to using a dokku managed crontab

- test/factories/site.rb
- test/factories/sites_neighbourhood.rb
- test/integration/sites_integration_test.rb
Fixes #877 
- Rename site_turves to sites_neighbourhood and correct factory model
- Add find_placecal test in sites_integration_test.rb
> Explicitly test /find-placecal endpoint

- app/components/event/event_component.rb
- app/controllers/admin/sites_controller.rb
- app/models/event.rb
- test/integration/admin/sites_integration_test.rb
- test/integration/events_integration_test.rb
> #884 - Fix descendants not showing on prospective region site

- README.md
- app/controllers/admin/partners_controller.rb
- app/helpers/partners_helper.rb
- app/helpers/users_helper.rb
- app/javascript/src/behaviors/behaviors.partner.js
- app/views/admin/partners/_form.html.erb
- app/views/admin/partners/_service_area_fields.html.erb
- test/integration/admin/partner_integration_test.rb
No more thousands of checkboxes when admins want to add or edit a
partners' service areas. Implements #898
> Use cocoon selector on partners form

- app/components/admin_index/_admin_index.html.erb
- app/datatables/user_datatable.rb
- app/views/admin/calendars/_form.html.erb
- app/views/admin/sites/_form.html.erb
- app/views/admin/users/profile.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/admin/_admin_topbar.html.erb
Topbar:
- Switch to using email address in topbar and clearly indicate if user is root (Fixes #903)
Users page:
- Moves the margin on the top buttons into a surrounding element puts them both on the same line in the user interface, otherwise the Facebook link looks wonky and weirdly offset
- Fixes broken search on users page due to Datatables AJAX error (Fixes #901)
Calendars edit page:
- Adds some leeway at the bottom between the lower end of page boundary and the update/delete buttons
Sites edit page:
- Link to (prospective) correct page in handbook of event sources (See: [Add Event Sources List](https://github.com/geeksforsocialchange/PlaceCal-Handbook/pull/5) )
Also amend `<br />` => `<br>`
> Fix some rough edges

- lib/tasks/db.rake
This file change amends the `rake db:dump_production` group of tasks to correct the SSH port, as well as allowing `ssh config` items to be preferentially chosen by the user (For example, the usage of `ssh placecal`, instead of `ssh root@placecal.org -p 666 -i (identity file)`
> Correct db-dump procedure for SSH port, and allow use of SSH config bindings

- app/components/admin_index/_admin_index.html.erb
- app/controllers/admin/calendars_controller.rb
- app/controllers/admin/sites_controller.rb
- app/controllers/admin/tags_controller.rb
- app/datatables/calendar_datatable.rb
- app/datatables/datatable.rb
- app/datatables/site_datatable.rb
- app/datatables/tag_datatable.rb
- app/datatables/user_datatable.rb
- app/views/admin/calendars/index.html.erb
- app/views/admin/sites/index.html.erb
- app/views/admin/tags/index.html.erb
- app/views/layouts/admin/_datatable.html.erb
- Adds Datatables for Calendars, Tags, Sites
- Fixes small bug where clicking on admin_role in Users would cause an AJAX error
- Alter Datatables partial to add the extra links for Calendars (Facebook importer -- perhaps no longer needed? Separate ticket territory :slightly_smiling_face: )
Fixes #921
> Add Datatables for Calendars, Tags, and Sites

- app/graphql/types/address_type.rb
- app/graphql/types/event_type.rb
- app/graphql/types/partner_type.rb
- app/graphql/types/query_type.rb
- test/integration/graphql/event_integration_test.rb
You can now query the API with things like this for event index:
```
query {
allEvents {
id
summary
description
}
}
```
And this for show event:
```
query {
event(id:123) {
id
summary
description
address {
streetAddress
city
postcode
}
}
}
```
> Add events to GraphQL endpoint

- app/assets/stylesheets/base/turf.sass
- app/components/place_partner_preview/_place_partner_preview.html.erb
- app/components/place_partner_preview/place_partner_preview_component.rb
- app/helpers/partners_helper.rb
- app/models/partner.rb
- app/views/admin/users/profile.html.erb
- app/views/partners/index.html.erb
- app/views/partners/show.html.erb
- test/helpers/partners_helper_test.rb
- test/integration/admin/user_integration_test.rb
- test/integration/partners_integration_test.rb
On guest users partner index page when seeing partners if the partner has a service area this now appears as a lozenge like the neighbourhood does (if present).
Things not covered in this PR:
* styling
* business logic covering how partners must have at least one of service_area or address
> Show service area information on location lozenges

- app/controllers/admin/users_controller.rb
- app/helpers/calendars_helper.rb
- app/helpers/tags_helper.rb
- app/helpers/users_helper.rb
- app/models/calendar.rb
- app/models/tag.rb
- app/models/tags_user.rb
- app/models/user.rb
- app/views/admin/calendars/_form.html.erb
- app/views/admin/tags/_form.html.erb
- app/views/admin/users/_form.html.erb
- db/migrate/20220221063323_add_id_to_tags_users.rb
- db/schema.rb
- test/integration/admin/user_integration_test.rb
Fixes #971 
- Add TagsUser model
- Pluralisation fixed courtesey of Kim
- Edit User, Tag models to fix relation
- Add Tags to User's form
- Clean up User form
- Move roles and tags out of user's controller into helper
- Properly policy scope tags
- Add role_label Singleton
- Switch to using two column layout
- Fix options_for_neighbourhoods formatting
- Fix strategy_label formatting
- Add TagsUsers to Tag model and form
- Add edit_permission_label singleton to Tag
- Add edit_permission radio buttons to Tags form
> Add TagUser model + tags to user's form. Clean up stuff

- app/models/user.rb
- app/policies/partner_policy.rb
- test/models/user_test.rb
- test/policies/partner_policy_test.rb
Implements #993 - users can only modify partners that they have links to
> User service area partner admin

- app/models/partner.rb
- test/fixtures/neighbourhoods.yml
- test/models/partner_test.rb
- test/test_helper.rb
Implements part 1 of #999 - Partners can be found via service area and address
> Site lookup Partners now includes service areas

- app/controllers/graphql_controller.rb
So you no longer need to provide any authentication token.
> Bypass rails authentication for graphql endpoint

- app/controllers/admin/calendars_controller.rb
- test/integration/admin/calendars_integration_test.rb
On the admin calendar edit page the form pre-fills the partner select
box correctly.
> Fix calendar organiser preselect bug

- app/models/partner.rb
- test/models/partner_test.rb
No restriction on needing to be in user's neighbourhoods
Implements fix for #1011
> Root users can assign service areas at will

- app/controllers/admin/partners_controller.rb
- app/datatables/partner_datatable.rb
- app/helpers/partners_helper.rb
- app/views/admin/users/profile.html.erb
- test/integration/admin/partner_integration_test.rb
Fixes #1033
- Adds tag preselection for tag_admin tags to Partners create form
- Adds tags listing to users profile
- Refactors partner integration tests to be cleaner and more in-line with the rest of the codebase
- Fix link to neighbourhood entry on the partners page
- Fixes Datatable search on Calendar entries
> Tag Preselection and Datatables search fix

- lib/tasks/db.rake
- Fixes a reference to `placecal-db` that should be `placecal-db2` for production
- Adds `rake db:sync_prod_staging` which directly synchronizes from production to staging without taking a (local) backup (it backs up to a file on the staging server instead)
Fixes #1060
> Fix rake db:* tasks reference to production database; Add direct synchronisation task

- app/models/event.rb
- app/models/partner.rb
- app/models/site.rb
- test/integration/partners_integration_test.rb
Fixes #1042 
- Fix badges not displaying properly for region sites
- Adds function `owned_neighbourhoods` to `Site` model
- Simplify some code to use `site.owned_neighbourhoods` instead
> Fix badges + simplify some code

- app/graphql/types/address_type.rb
- app/graphql/types/contact_type.rb
- app/graphql/types/event_queries.rb
- app/graphql/types/event_type.rb
- app/graphql/types/neighbourhood_type.rb
- app/graphql/types/opening_hours_type.rb
- app/graphql/types/partner_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/site_type.rb
- doc/index.md
Implements #997 - puts description fields on all the graphql parts so when you're in the graphiql page (on localhost) you can slide open the 'docs' tab and peruse the structures easily
> GraphQL documentation

- app/models/partner.rb
- test/controllers/admin/partners_controller_test.rb
- test/integration/admin/partner_integration_test.rb
- test/models/partner_test.rb
- test/test_helper.rb
Fixes #1037 
- root users can modify a partner that is not in their neighbourhoods
- users can change partner addresses via both street address and postcode
> Root user neighbourhoods bug

- app/graphql/types/query_type.rb
- app/models/article.rb
- test/integration/graphql/article_query_type_test.rb
Implements #1094.
New `allArticles` endpoint of type `[ArticleType]`. Just returns whatever is in the articles table.
> Reading articles through the GQL API

- app/models/event.rb
- test/models/events_test.rb
Fixes #1114
An action was attempting to read `location` from an event object, which did not exist but has now been implemented (+ tests).
> Fixed bug in ICS event download action

- app/controllers/admin/articles_controller.rb
- app/controllers/admin/partners_controller.rb
- app/graphql/types/article_type.rb
- app/models/article.rb
- app/policies/article_policy.rb
- app/uploaders/article_header_uploader.rb
- app/uploaders/article_image_uploader.rb
- app/views/admin/articles/_form.html.erb
- db/migrate/20220405102801_add_article_header_to_articles.rb
- db/schema.rb
- test/integration/admin/sites_integration_test.rb
- test/integration/graphql/article_query_type_test.rb
- test/integration/graphql/partners_integration_test.rb
- test/test_helper.rb
Fixes #1108 
- Add `ArticleHeaderUploader`, make sure it properly crops and centers
- Add `article_image` field to Article, policy code, controller, etc.
- Add `highres_image` to Article for GraphQL
- Guard `author_name` to return empty string for GraphQL in Articles
- Add `article_image` upload button and preview to view code 
- Add `image` field and correct `author` field type in GraphQL
- Also align the arguments of a method call when they span more than one line
- Change `author_name` to return an empty string as the field is required
- Add deep testing of Article models returned from GraphQL
- Rename `verify_field_presence` -> `assert_field_equals` (checked with Ivan :slightly_smiling_face:)
- Pull out `assert_field_equals` into `test_helper.rb` to be used in other tests
- Add …
> Articles now have Image Headers

- app/helpers/partners_helper.rb
- app/models/partner.rb
- app/models/site.rb
- app/views/admin/partners/_service_area_fields.html.erb
- app/views/admin/partners/edit.html.erb
- test/controllers/admin/partner_edit_site_test.rb
- test/integration/admin/partner_integration_test.rb
- Add owned_neighbourhood_ids to Partner model
- Correct sites_that_contain_partner to use GROUP BY to avoid duplicates
- Correct sites_that_contain_partner to use owned_neighbourhood_ids
- Add site_links to Partners helper, Partners admin edit screen
- Add test for admin interface Sites listing via service_areas
- Slightly refactor test for Partner admin interface sites listing
- Document stuff
- Scopes for partner model
- Document sites_that_contain_partner
- Document find_by_request
> Partner admin interface site duplicates

- app/models/article.rb
- app/models/article_tag.rb
- app/models/tag.rb
- app/policies/article_policy.rb
- app/views/admin/articles/_form.html.erb
- db/migrate/20220406135448_create_article_tags.rb
- db/schema.rb
- test/controllers/admin/articles_controller_test.rb
- test/integration/graphql/event_integration_test.rb
- Add ArticleTags relation via a migration
- Add policy code and document existing policy funcs :)
- Add view code (split into a side by side with Partners -- text will
need workshopping maybe)
- Add some improved coverage in the Controller tests for checking we can
edit partner_ids and tag_ids for root + editor (WILLFIX,TODO on
expanding that)
- Some formatting stuff
> Articles can have tags (part one!)

- app/assets/stylesheets/home/_form.sass
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users/auth_common.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/invitations_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/sessions_controller.rb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- test/integration/users_log_in_go_to_admin_site_test.rb
- test/integration/users_login_on_site_test.rb
> Make login and password reset processes nicer

- app/graphql/types/address_type.rb
- app/graphql/types/geo_coordinates_type.rb
- app/graphql/types/opening_hours_type.rb
- app/graphql/types/partner_type.rb
- test/integration/graphql/partners_integration_test.rb
- test/test_helper.rb
Fixes #1165
- Add geo field to partners_type
- Add GeoCoordinatesType
- Add tests (fixup some of the existing tests as well)
- Some formatting stuff
> Add GeoCoordinates to Partner (GraphQL)

- app/graphql/types/address_type.rb
- app/graphql/types/partner_type.rb
- app/models/address.rb
- test/integration/graphql/event_integration_test.rb
- test/integration/graphql/partners_integration_test.rb
Fixes #1165
- Removes `GeoCoordinates` type from `partner_type`
- Adds `GeoCoordinates` type into `address_type`
- Adds gql test for `geo` field returned via `eventsConnection`
- Small formatting changes on `address.rb`
- Remove some redunant gql testing code
- Remove `verify_correct_number_of_items` and swap out for `assert_equals`
(They do the same thing)
- Switch to using `refute_field` for result `errors`, make sure we
consistently test for result error blocks
- Remove redundant `Partner.transaction` blocks
- Add TODO for property depth testing rather than just array length
testing (The latter is shallow and we might miss some bugs)
> Move GeoCoordinates type into AddressType

- app/jobs/calendar_importer/events/meetup_event.rb
Meetup events with missing durations end at the same time they start
(as a default value)
> Meetup.com events without an end time don't break the importer

- app/helpers/calendars_helper.rb
- app/models/partner.rb
- test/helpers/calendars_helper_test.rb
Fixes #1185 
In calendar edit/new page, only show partners (locations) that have addresses
> Filtering partners with addresses

- app/javascript/src/calendar-form.js
It was causing some hiccoughs when the strategy was saved as it would stop the new selected value from being re-selected on page load.
Took out the Vue code that did the hiding/showing
> Remove buggy JS on calendar strategy selector

- app/jobs/calendar_importer/event_resolver.rb
- app/models/event.rb
This is a workaround. We should remove this in the future. I consider
this the second most horrible code I've intentionally written.
- EventResolver#determine_location_for_strategy - passthrough 'event'
strategy if no location / place / address
- Bypass validation error if strategy == 'event'
- EventResolver#save_all_occurences - Directly add error to notices
> Passthrough 'event' strategy if no location

- app/policies/user_policy.rb
- test/controllers/admin/users_controller_test.rb
- Fixes `user_policy#permitted_attributes` and `user_policy#permitted_attributes_for_create`
- Adds test for `partner_ids` property when creating a new user for `neighbourhood_admin`
- Adds test for `partner_ids`, `neighbourhood_ids`, and `tag_ids` when creating a new user for `root`
> 'Invite new partner admin' preselection doesn't stick

- config/robots/robots.production.txt
Adds a robots.txt to production to disallow web search engine scrapers from the /events/ and /assets/ pages. This is to stop us losing access to Rollbar when events on the server are refreshed and the ids become invalid. Assets has been denied to see if it reduces illegitimate bot scraping attempts.
Fixes #1230
> Stop semrushbot/ahrefsbot/bing spam after calendar reimport

- app/helpers/calendars_helper.rb
- app/jobs/calendar_importer/calendar_importer_task.rb
- app/jobs/calendar_importer/event_resolver.rb
- app/models/calendar.rb
- app/models/event.rb
- app/models/online_address.rb
- app/models/tag.rb
- app/views/admin/calendars/_status.html.erb
- config/initializers/delayed_job_config.rb
- db/migrate/20220512144807_create_online_addresses.rb
- db/schema.rb
- lib/tasks/workers.rake
- test/factories/online_addresses.rb
- test/helpers/calendars_helper_test.rb
- test/jobs/calendar_importer/event_resolver_test.rb
- test/models/address_test.rb
- test/models/online_address_test.rb
Fixes #1238
Draft because I want to isolate a bug that's happening and confirm I didn't add it lol
- refactor: strategy refactor
- feat: add online address model
- feat: add 'online_only' strategy to importer
- chore: make rake shut up about pundit
- feat: make calendar clear to user in error log
- feat: make import status more visible (bigger)
- feat: limit delayed job run time
- feat: add purge rake task for delayed jobs
- feat: add task for fixing calendar status
> 1238 - Add OnlineAddress and online_only import strategy

- app/jobs/calendar_importer/event_resolver.rb
- app/models/address.rb
- app/models/event.rb
- test/jobs/calendar_importer/event_resolver_strategy_test.rb
When an event is imported a factory is employed to give the event the
correct place/address. Therefore the event itself no longer has this
business logic in it
Fixes #1244
> Bug: Events should not set their own address

- app/jobs/calendar_importer/calendar_importer_task.rb
- app/jobs/calendar_importer/event_resolver.rb
Fixes #1257
Fixes bug with the importer where an `OnlineAddress` is created but not properly linked with an event. More broadly, it fixes a previously undetected class of error where changes to past events (even ones that may change the `dtstart`/`dtend` to a time in the future), were not properly saved.
This bug occurs because the importer was not considering events that are not upcoming, when it tries to detect duplicate events, which would mean that the event id is not properly assigned. The event change would then be rejected as the lack of a pre-existing event id would generate a `create` change, which fails validation because the details for that event already exist to us.
> Fix importer bug where event changes are not saved

- app/datatables/tag_datatable.rb
- app/models/tag.rb
- app/policies/tag_policy.rb
- app/views/admin/tags/_form.html.erb
- app/views/admin/tags/edit.html.erb
- app/views/admin/tags/index.html.erb
- db/migrate/20220607161025_add_system_flag_to_tags.rb
- db/schema.rb
- test/factories/tag.rb
- test/integration/admin/tags_integration_test.rb
- test/models/tag_test.rb
- test/policies/tag_policy_test.rb
Implements #1028 
Tags now have a system_tag flag. System tags can only be modified by root users.
> Allow tags to be set as uneditable

- app/components/event/event_component.rb
- app/graphql/types/event_type.rb
- app/helpers/events_helper.rb
- app/jobs/calendar_importer/calendar_importer.rb
- app/jobs/calendar_importer/event_resolver.rb
- app/jobs/calendar_importer/events/eventbrite_event.rb
- app/jobs/calendar_importer/events/ics_event.rb
- app/jobs/calendar_importer/events/meetup_event.rb
- app/jobs/calendar_importer_job.rb
- app/models/online_address.rb
- app/views/events/show.html.erb
- db/migrate/20220524160826_add_is_stream_to_online_address.rb
- db/migrate/20220524160826_add_link_type_to_online_address.rb
- db/schema.rb
- lib/tasks/events.rake
- test/integration/graphql/event_integration_test.rb
Fixes #1240
feat: make online_address visible in graphql
feat: add is_stream to online address
refactor: cleanup graphql tests
fix: major bug where room_number strategies failed (silently!)
feat: show link to online address on main site
> Make online address visible in PlaceCal/GraphQL

- app/views/admin/partners/edit.html.erb
> fix: use email rather than name when displaying partners users

- app/components/admin_flash/admin_flash.sass
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- config/environments/development.rb
Fixes #1295 
- no more stimulus on reset password form or change password form
- put in styling for the flashes on root placecal site so you can see them
- changed (development environment) active mailer missconfiguration. now uses http://lvh.me:3000
> Reset password form bug

- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/news_controller.rb
- app/controllers/partners_controller.rb
- config/routes.rb
- test/controllers/events_controller_test.rb
- test/controllers/partners_controller_test.rb
- test/integration/event_integration_test.rb
- test/integration/events_integration_test.rb
- test/integration/partner_integration_test.rb
- test/integration/partners_integration_test.rb
- test/test_helper.rb
Redirect to find-my-placecal endpoint for `/events`, `/partners` and `/news`
Fixes #1333
> fix: redirect to find my placecal on main site

- app/models/partner.rb
- test/models/partner_test.rb
When parsing opening times, protect against badly formed JSON that may
have been received by the calendar importer.
Fixes #1339
> Guards against badly formed JSON in Partners

- Gemfile.lock
- app/graphql/types/query_type.rb
- app/helpers/users_helper.rb
- app/models/article.rb
- app/models/partner.rb
- app/views/admin/pages/home.html.erb
- test/integration/admin/home_integration_test.rb
- test/models/article_test.rb
- test/models/partner_test.rb
Some of the data in partner `opening_times` fields was badly formed.
When citizens log in and have no tags, neighbourhoods or partners they should see a message on the dashboard and their profile page. This is not the case if the user has the root role.
When an article has the `foo` tag applied and a site has a `foo` tag in its selected tags field, then that article should appear on the site, regardless of location. This is in addition to the previous behaviour of finding articles published from partners that have neighbourhoods in the Site's neighbourhoods.
As an extension of 1364: users with editor roles do not see the blank content warning.
> Production deployment 6th July 2022

- app/controllers/application_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/concerns/map_markers.rb
- app/controllers/events_controller.rb
- app/controllers/partners_controller.rb
- test/controllers/concerns/map_markers_concern_test.rb
Fixes #1346
* On Partners index page: only show partners that have physical addresses (filter out Partners with any service areas)
* On Partners show page: show all markers from physical addresses and service areas
> Partners with service areas appear on maps

- app/controllers/admin/calendars_controller.rb
- app/views/admin/calendars/_form.html.erb
- db/migrate/20220720151156_remove_calendar_contact_info_fields.rb
- db/schema.rb
- test/factories/calendar.rb
Fixes #1338 
- Change of copy on the 'public contact' area
- Removal of partnership contact form area
> Simplify and clarify calendar contact form information

- Gemfile.lock
Homebrew no longer has a `postgresql` package, instead requiring version specification (eg `postgresql@14`). `pg` 1.3.5 looks for `libpq` in at `$(brew --prefix)/opt/postgresql/` but there's nothing there anymore. The `pg` gem resolved this in later versions of itself.
> Use pg 1.4.3

- app/components/computer_access/_computer_access.html.erb
- app/components/free_public_wifi/_free_public_wifi.html.erb
- app/controllers/sites_controller.rb
- app/models/partner.rb
- test/integration/sites_integration_test.rb
- test/models/partner_site_with_tag_scope_test.rb
Fixes #1443 
A scope on partners that returns partners for a given site with a single (site) tag present. Partners can have either address OR service area in sites neighbourhoods
> Fix: scoping on site partners by tag

- .env.example
- README.md
- bin/setup
- bin/update
- bin/yarn
- Clarify Postgresql via Docker is optional
- Use bin scripts for setup and updates
> Automate setup

- app/models/partner.rb
- app/views/admin/partners/_opening_times.html.erb
- test/models/partner_test.rb
- test/system/admin/partner_test.rb
- test/test_helper.rb
Closes #1460 
On admin partner edit page, partners with missing opening times value would crash JS and cause tags selector to fail.
Quick sanitisation of value and a system test to cover that scenario
> Fix: partner tag selector bug

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- test/system/create_admin_users_test.rb
In the test environment:
```
From: .../github.com/geeksforsocialchange/PlaceCal/test/system/create_admin_users_test.rb:48 CreateAdminUsersTest#test_visiting_the_index:
43:
44:     invitation_url = extract_invitation_link_from(email)
45:     # puts "invitation_url=#{invitation_url}"
46:     assert invitation_url, 'Could not find invitation URL in email'
47:
=> 48:     binding.pry
49:
50:     # set password
51:     visit invitation_url
52:     fill_in 'New password', with: 'password'
53:     fill_in 'Repeat password', with: 'password'
[1] pry(#<CreateAdminUsersTest>)> invitation_url
=> "https://127.0.0.1:52983/users/invitation/accept?invitation_token=fCX4-BqSAwyCwzmLNGqo\r"
```
This was due to ActionMailer using the default config, which we need to override.
> Inherit default route options for ActionMailer from routes

- app/views/admin/calendars/_form.html.erb
fixes #1498
- update link to placecal handbook.
- add examples of url format to handbook.
- confirm that events are now pulling through from the url noted in the issue.
> Update link to PlaceCal handbook on calendar admin page

- app/jobs/calendar_importer/parsers/ics.rb
Fixes #1493 
There was a bug where non-string responses were being passed into string expecting methods (and crashing). Turns out the method in question was already defined on a base class in a more robust manner. So let's use that!
> Fix: Don't try to hash non string inputs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/technical_debt.md
This sets the "needs triage" label on all new issues to support that as a new workflow.
It also created a new technical debt template to reduce the amount of skipping outside of the templates being done.
> Improve issue templates

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test.yml
- bin/test
I noticed that the new workflows weren't running. I think this is due to the test workflow being "called" `.github/workflow/test.yml` (or something) and not just `test`. So we give the workflow an explicit name here instead, so we can reference that.
While I was looking at that I realized that we needed to also only run on success, so I've implemented that, too.
> Fix deployment actions

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- .github/workflows/test.yml
> Hopefully fix deployment workflows

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
dokku/github-action pushes a specific commit and needs to have a local copy of that commit to do so.
Relates to #1522
> Fetch the full Git history for deployments

- app/jobs/calendar_importer/events/base.rb
- test/jobs/calendar_importer/event_base_html_sanitize_test.rb
Fixes #1530 
Strip HTML tags of their attributes (but keep <a> tag hrefs)
> Fix: cleaning up HTML before parsing into markdown

- app/jobs/calendar_importer/events/base.rb
- test/jobs/calendar_importer/event_base_html_sanitize_test.rb
Closes #1533 
Assume summary field could contain risky content (like HTML) and scrub that out before saving in DB.
> Strip all HTML out of summary fields

- app/controllers/partners_controller.rb
- app/models/partner.rb
- app/models/site.rb
Fixes #1532 
When pulling neighbourhoods out of the database only instantiate the fields that are required so ActiveRecord doesn't have to parse unused values
> Speeding up partner index page load time

- package.json
This will hopefully reduce the frequency of committing changes without running Rubocop first.
> Correct Ruby on commit

- Gemfile
- Gemfile.lock
We have a lockfile to pin them for us, so we don't need to pin them.
This should allow Renovate to automerge updates to them if they pass.
> Stop pinning gems

- test/integration/graphql/event_integration_test.rb
- test/test_helper.rb
see #1572
> Tests are configured to freeze time to a fixed, known date
> tests that reference time use 2022/11/8 (transDim launch)

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- lib/tasks/doc.rake
- test/controllers/components_test.rb
Devs can now run `rails doc:generate` to generate HTML documentation.
> Documentation generator

- app/jobs/calendar_importer/parsers/squarespace.rb
Fixes #1617 
Some squarespace URLs already come to us with the source=json bit on the end so we shouldn't try to add it twice
> Squarespace URL normalizing bug fix

- .gitignore
I don't have tags set up on my system (maybe I should) but the current .gitignore breaks telescope which I use to search.
Does tags just live in a folder at root? would this meet everyones of our needs?
> Make rg search respect gitignore

- app/helpers/partners_helper.rb
- app/models/tag.rb
- app/views/admin/partners/_form.html.erb
- test/integration/admin/partner_integration_test.rb
- test/system/admin/partner_test.rb
Closes #1702 
Admins can now see what type all of the tags they are selecting from
> Make Tag type visible on Partner edit page

- app/helpers/tags_helper.rb
- app/views/admin/tags/_form.html.erb
- test/integration/admin/tags_integration_test.rb
Closes #1711 
On admin edit tag page: only show 'Assigned Users' input if the Tag is a plain tag or a Partnership.
> Hide Tag "Assigned Users" field unless it's a Partnership

- .gitignore
- README.md
- makefile
fixes #1748
This PR aims to improve the setup & running experience for any future & current GFSC devs, especially those using docker. Using all of the helpful notes I've been given, I've distilled the list of things needed to be done to get a working version of PlaceCal with a copy of some viable data running locally. 
To enable quick replication of these steps I have also:
- simplified the readme by making explicit a quick setup route for GFSC developers, and extracting some of the larger chunks of code into a makefile
- Added a makefile that contains all the commands needed to set up a GFSC environment (contains no sensitive information)
- Added other commands to the makefile required to run & tear down the environment, set up a docker db
- Added Ivan's makefile commands to run tests …
> Update the readme + add a makefile to simplify setup

- app/models/tag.rb
- test/factories/tag.rb
- test/integration/event_site_integration_test.rb
- test/system/admin/tag_test.rb
fixes #1737
- add a validation on the model
- fix up our test data as a lot of the tags were being generated without a type
> make type mandatory on Tag

- app/policies/site_policy.rb
- test/integration/admin/sites_integration_test.rb
Fixes #1746 
- Modifies the site scope to allow access to only the sites a root user is an admin for if they are an admin for any
- If the root user is an admin for none, allows access to all sites
- Adds tests to assert working as expected
- We still have an 'Add new site' button visible for the site admin roots - is this functionality we want them to have, or should this be removed too?
- The original issue ticket asked for `"Create a partner"  and "create a calendar" links where the site list used to be` . After discussing as a team it was agreed that we didn't want to remove the site list completely for any root user, which I thought made this redundant. Im now wondering though which type of root user was this for the benefit of, and do we actually want this in addition to showing the …
> Only show client root users the sites they're an admin for

- app/models/tag.rb
- app/policies/tag_policy.rb
- test/models/tag_test.rb
fixes #1763 
- remove root user logic from policy scope
- exclude root user who is tag admin from receiving `Tag.all`
- add a tests to validate
> limit tags shown to root user if they are also a (Partnership)tag_admin

- app/controllers/admin/tags_controller.rb
- app/helpers/tags_helper.rb
- app/policies/tag_policy.rb
- test/controllers/admin/tags_controller_test.rb
- test/policies/tag_policy_test.rb
Fixes #1653
- Updates the tags policy to make `:partner_id` a permitted attribute for a `:partner_admin`. This allows them to add or remove a partner that they manage from a category or facility tag.
- Adds tests to assert that the tags policy is working correctly for a `:tag_admin` or `:partner_admin` user
- Removed a redundant line of code from the tag policy - note on which below.
- The two facility tags in our production copy db are currently also `system_tags` which means they cannot be edited from the tag dashboard, and so also cannot be assigned/removed from a partner from this interface. This feels like a subtly different bug - if I create a new `facility_tag` without a `system_tag` symbol then it works as expected. Do we want `partner_admins` to be able to attach/detach tags that …
> Allow partner admins to add & remove categories and facilities to partners from tags page

- app/components/paginator/paginator.sass
- app/controllers/partners_controller.rb
- app/views/partners/index.html.erb
- app/views/partners/tag.turbo_stream.erb
- config/routes.rb
- test/controllers/partners_controller_test.rb
- test/models/tag_test.rb
- test/test_helper.rb
fixes #1644
We had ambitions to make a snazzier UI but in the interest of getting something usable into the world I just reused the filter UI from the events page.
I touched a couple of files that are look out of scope.
- I had to increase the z index of the dropdown filter menu because when there are very few partners the map element sits over the top of it.
- Because I wanted to write some tests with multiple category tags I updated  the test_helper and that had a knock on effect in model/tag_test but I think it makes that test more comprehensive.
> feat: add ui for public to filter partners by category tag

- app/controllers/admin/pages_controller.rb
- app/models/user.rb
- app/policies/dashboard/site_policy.rb
- app/policies/site_policy.rb
- test/integration/admin/home_integration_test.rb
- test/integration/admin/sites_integration_test.rb
Fixes #1792
- Restores all sites to admin root users, regardless of whether or not they admin for them
- BUT restricts the sites they see from their dashboard, showing them only those they admin for here if they are a site admin for any.
- Adds tests to assert this is working as expected and removes now broken test making wrong assertion
Can whoever is checking this double check the acceptance criteria is definitely the desired behaviour :------)
> Show all sites to site admin root users from admin/sites page

- app/helpers/users_helper.rb
- test/integration/admin/sites_integration_test.rb
- test/system/admin/article_test.rb
- test/system/admin/site_test.rb
- test/system/admin/user_test.rb
fix #1734
- mimic the `options_for_tags` method we are using for partners
- update tests
> admin UI for indiviual sites is showing the tag type

- app/assets/stylesheets/base/buttons.sass
- app/assets/stylesheets/base/typography.sass
- app/components/breadcrumb/breadcrumb.sass
- app/views/partners/index.html.erb
fixes #1778
This issue is also described by David in #1780
- Add a link back to `/partners` labeled "Reset
- Some CSS fiddling to keep UI consistent, inputs were not using the correct font for example.
> add reset to partners category filter UI

- package.json
Our builds are failing at the moment because they are being built with the wrong version of node. My digging is leading me down the following path:
This step is failing because of this github action
This action is failing because this version of heroku is incompatible with this version of node, which is not the version we are using elsewhere in this project
This version of node is being used because we do not specify a version in engines in our package.json
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
> Fix wrong node version creeping into builds

- RELEASING.md
fixes #1783 
Adds a line to the releasing document to prompt us to double check the node versions are all in sync before releasing so that we don't run into a problem again with different environments struggling with different set ups.
> ensure node versions don't get out of step in different environments

- app/components/case_study_component/case_study_component.html.erb
- app/components/case_study_component/case_study_component.scss
- app/components/featured_partnerships_component/featured_partnerships_component.html.erb
- app/components/featured_partnerships_component/featured_partnerships_component.scss
- app/components/four_col_grid_component.rb
- app/components/four_col_grid_component/four_col_grid_component.html.erb
- app/components/four_col_grid_component/four_col_grid_component.scss
- app/components/partnership_card_component.rb
- app/components/partnership_card_component/partnership_card_component.html.erb
- app/components/partnership_card_component/partnership_card_component.scss
- app/views/pages/home.html.erb
Fixes #1892 
Fixes #1896
- Fixes dodgy urls forming with double `//` by checking url & only applying if necessary
- Also hides content of @site from partnership component view & only passes what is necessary
- Changes `interest-based calendars` to `curated calendars`
- Moves trans dimension case study up the page & adds a banner title to it
- Oh yes - and limited neighbourhood cards on homepage to 4 - just to avoid any extra ones accidentally creeping in
> Curated calendars improvements

- app/controllers/concerns/partner_category_filter.rb
- app/controllers/partners_controller.rb
- app/models/neighbourhood.rb
- package.json
- test/controllers/concerns/partner_category_filter_test.rb
- test/controllers/partners_controller_test.rb
- test/integration/partner_category_filter_test.rb
Fixes #1909
On site partners page: the filter only shows categories that have been applied to partners who have an address or service area in the site's neighbourhood pool.
> Refinement of filter category selection

- package.json
## Description
- Revert change made in [#1910](https://github.com/geeksforsocialchange/PlaceCal/pull/1910/commits/ca074c5fd44476c93ee6d5493f5daa6b73a339a2) to add yarn as a dev dependency to prevent build breaking on staging
> Remove yarn as dependency

- app/controllers/concerns/partner_category_filter.rb
- test/controllers/concerns/partner_category_filter_test.rb
Fixes #1917 
Partner category filter `categories` method uses the sites' hierarchical neighbourhood scope to retrieve all of the sites neighbourhoods
> Widen partner category scope

- app/models/calendar.rb
- test/models/calendar_test.rb
Closes #1121
When calendar changes state, leave updated_at alone. And tests
> Stop touching calendar updated_at in state machine

- package.json
Closes #1971 
When linting in before-commit hook, make rubocop honor the ignore list so it doesn't try to lint things like `db/schema.rb` and so on.
> Fix husky lint check

- app/helpers/neighbourhoods_helper.rb
- app/helpers/partners_helper.rb
- app/helpers/sites_helper.rb
- app/helpers/users_helper.rb
- app/models/neighbourhood.rb
- app/views/admin/neighbourhoods/index.html.erb
- app/views/admin/partners/_form.html.erb
- app/views/admin/partners/_service_area_fields.html.erb
- app/views/admin/partners/edit.html.erb
- app/views/admin/sites/_form.html.erb
- app/views/admin/sites/_sites_neighbourhood_fields.html.erb
- app/views/admin/users/_form.html.erb
- doc/updating-neighbourhoods.md
- lib/tasks/placecal.rake
- test/controllers/admin/partner_edit_site_test.rb
- test/factories/neighbourhood.rb
- test/fixtures/neighbourhoods.yml
- test/models/neighbourhoods_test.rb
Closes #2017 
For such a simple issue this has struck a nerve at the core of our data models.
Tasks covered:
- latest neighbourhood release date is defined in Neighbourhood model
- a scope to only find `latest_release` in Neighbourhood
- update to UX so neighbourhood pickers only show latest neighbourhoods BUT will also show only the legacy neighbourhoods that have already been selected by that entity.
- sites, partners (service areas) and users
- latest version is displayed on admin neighbourhood page
- Neighbourhood updating documentation: added text covering how to set the `latest_release` date in the Neighbourhood model
There is a rake task `rails placecal:find_obsolete_neighbourhoods` that will look at every user, site and partner to see if they are linking to a legacy neighbourhood. …
> Duplicate neighbourhoods

- app/policies/site_policy.rb
- app/views/admin/sites/_form.html.erb
- test/integration/admin/sites_integration_test.rb
fixes #2108 
Attribute | Root | site_admin | verified/ticketed
| ---|---|---|---
| `badge_zoom_level` | ✅ | ✅ | ✅ | 
| `description` | ✅ | ✅ |  ✅ |
| `footer_logo` | ✅ | ✅ |  ✅ |
| `hero_image_credit` | ✅ | ✅ | ✅ | 
| `hero_image` | ✅ | ✅ | ✅ | 
| `hero_text` | ✅ | ✅ | ✅ | 
| `logo` | ✅ | ✅ | ✅ | ✅ | 
| `name` | ✅ | ✅ |✅ | 
| `place_name` | ✅ | ✅ | ✅ | 
| `tagline` | ✅ | ✅ | ✅ | 
| `theme` | ✅ | ✅ | ✅ | 
| `is_published`  | ✅ | ✅  | ✅ | 
| "other neighbourhoods" | ✅ | ❌ | ✅  |
| "tags" -> "partnerships" | ✅ | ❌ |  ✅  |
| `domain` | ✅ | ❌ | ✅  |
| `site_admin_id` | ✅ | ❌ |  ✅  |
| `slug` | ✅ | ❌ | ✅  |
| "main neighbourhood" | ❌ | ❌ | ✅ |
> site admin access 

- app/controllers/admin/partners_controller.rb
- app/models/partner.rb
- test/controllers/admin/partners_controller_test.rb
Fixes #2124
A neighbourhood admin is now prevented from removing all service areas they admin for from their partners, unless a partner's address is within their neighbourhood.
This was really tricky - you can't validate an association in the same way as the rest of the record so it has to be assessed after everything else is validated. Obviously this is not perfect because the service areas have to be evaluated in conjunction with the address, so users are not going to be able to see all validation warnings at once. 
Also I had to re-render the edit page instead of just returning it with errors in the normal way because if I did not, everything (the record, the database, and the params) was out of sync when I rendered the page and all sorts of nasty unexpected things were happening.
> Neighbourhood admins cannot remove all of their service areas from partners with no addresses

- config/environments/staging.rb
Closes #2133 
In staging environment initializer, set the URL the mailer will use to generate asset links from the base application URL.
> Staging mailer asset host configuration

- app/controllers/admin/partners_controller.rb
- app/models/user.rb
- app/views/admin/partners/_form.html.erb
- app/views/admin/partners/_service_area_fields.html.erb
- test/controllers/admin/partner_edit_site_test.rb
- test/controllers/admin/partners_controller_test.rb
- test/integration/admin/user_integration_test.rb
- test/models/user_test.rb
Fixes #2123 
What a bug! Neighbourhood admins used to see an incorrect list of service areas for partners - it would replace actual neighbourhoods with neighbourhoods owned only by the admin.
They can now see all of the neighbourhoods, but they cannot remove or modify neighbourhoods they do not admin for. They CAN add neighbourhoods they do not admin for, but only ones that are already owned by the partner, ie: no change. This does cause the validation to fail, preventing a partner save, but they can refresh the page and everything is fine. I will raise a separate ticket to fix this in a future iteration as it is annoying but does not actually break anything, and the likelihood that admins are going to be trying to add the same service area multiple times is really slim.
Partner admins …
> All neighbourhoods on partners are shown, editing these is limited for neighbourhood admins

- app/policies/calendar_policy.rb
- test/factories/calendar.rb
- test/policies/calendar_policy_test.rb
- test/policies/partner_policy_test.rb
Fixes #2132 
Admins could create a calendar and then lose it because it was assigned to a partner whose service address is in their neighbourhood but whose address is not!
This updates the calendar policy to make the list of visible calendars include those which are attached to a partner whose service area is in an admins neighbourhood.
Also it adds some tests.
> Update calendar policy to allow neighbourhood admins to see all calendars attached to their partners

- app/models/user.rb
- app/policies/partner_policy.rb
- app/views/admin/partners/_form.html.erb
- test/controllers/admin/partners_controller_test.rb
- test/integration/admin/partner_integration_test.rb
- test/integration/admin/user_integration_test.rb
- test/models/user_test.rb
- test/policies/partner_policy_test.rb
- test/system/admin/partner_test.rb
Closes #2130 
- Lets neighbourhood admins delete partners, but ONLY if those partners exist only within their neighbourhoods
- Lets partner admins delete partners
- Adds some explanatory text for how to contact us if a user wants to delete a partner and can't
I can certainly see a future scenario where this becomes a nuisance - for example, one of your partner admins has decided their service should operate outside of your remit and you want to shut them down. Neighbourhood admins can control this by making themselves a partner admin and then deleting the partner, but this is also open to abuse. It would be good to consider in the next architecture/permissions cycle what we think the best approach to handling these sorts of situations might be!
> Allow deletion of a partner by a neighbourhood admin when they are the only possible Neighbourhood admin for that partner

- Gemfile
- Gemfile.lock
- config/environments/test.rb
Closes #2162 
Removed unused gems
I found running these commands where necessary to expunge the old gems / assets from being loaded (during tests):
```bash
rbenv gemset delete 3.1.2 gfsc-placecal # purge old/unused gems
bundle
rails assets:clobber # force clean assets
rails tmp:cache:clear # will remove coffee script remnants
```
The `rails tmp:cache:clear` may have to be run prior to deployment to staging / production.
> Removing unused gems

- app/policies/tag_policy.rb
- app/views/admin/tags/_form.html.erb
- test/controllers/admin/tags_controller_test.rb
- test/integration/admin/tags_integration_test.rb
- test/policies/tag_policy_test.rb
fixes #1712 
- Only roots see the admin ui https://admin.placecal.org/tags*
- Only roots can create and delete Tags
- Only roots can edit tag related properties (name, slug, description, type)
- Partnership Admins should be able to add their partnership tag to partners (via partner edit page)
- Only roots can add partnership tags to users
> 1712 restrict tags to roots

- app/helpers/partners_helper.rb
- app/models/site.rb
- test/models/site_test.rb
fixes #2151 
We were checking the partners neighborhood ids against the sites neighborhood ids but this failed when the site had a neighborhood that encompassed other smaller neighborhoods. From the partner we would have needed to expand all the way to the root neighborhood and check if any sites existed.
It feels like there's probably some more efficient way of doing this,  we bounce back and forth between the sites and partners rebuilding the entire world just to scope it back down again. So open to an obvious answer I'm missing but also didn't want to start down a  rabbithole.
> fix: missing sites from partners @sites

- app/helpers/users_helper.rb
- app/models/tag.rb
- app/models/user.rb
- app/policies/partner_policy.rb
- app/policies/user_policy.rb
- app/views/admin/users/profile.html.erb
- test/controllers/admin/tags_controller_test.rb
- test/factories/user.rb
- test/models/tag_test.rb
- test/models/user_test.rb
- test/policies/partner_policy_test.rb
- test/policies/tag_policy_test.rb
- test/test_helper.rb
fixes #2168
This PR begins the work to reinstate partnership admins by making the only partners visible to them ones that have the tag that they own, and are in neighbourhoods within their scope. 
I began by defining a generic partnership admin as a tag admin who only owns partnership tags. Since it is technically impossible for a user to own any other type of tag, this is a bit belt and braces, but I thought it made it clearer what it meant to be a partnership admin. I then removed all references to tag admins and replaced them with references to the partnership admin.
I tweaked how we define a `neighbourhood_admin_for_partner` class method on the user to only return true for users without partnership tags, and added a `partnership_admin_for_partner` class method that will only return …
> Only show tagged partners to partnership admins

- app/models/partner.rb
- test/models/partner_test.rb
fixes #2171
Added a validation to partner model that check if user is a `partnership_admin` and prevents them creating partners outside their partnership. The other AC are already in place based on the work we did on `neighbourhood_admin` permissions.
>  partnership_admin create partners permissions

- app/controllers/admin/partners_controller.rb
- app/helpers/partners_helper.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/partner_tags_controller.js
- app/views/admin/partners/_form.html.erb
- test/helpers/partners_helper_test.rb
fixes #2174
- ensures root users can still add/remove any tag
- ensures partner admins can still add any category or facility tag and remove any partnership tags
- allows partnership admins to edit tags without accidentally removing tags they can't see in the process
- prevents partnership admins from removing partnership tags that don't belong to them
- warns partnership admins if tag removal is likely to boot a partner out of their scope
I've used a bespoke select2 style controller for this again, like we did for controlling the partners that users admin for. This is mainly so there is instant and obvious feedback, and because we don't actually need to make these moves impossible at a database level, we just want to ensure admin users are fully aware of how certain actions will impact …
> Fix the tag editing capabilities of everyone on a partner

- app/policies/user_policy.rb
- test/policies/user_policy_test.rb
Fixes #2169 
- Shows partnership admins only users that are partner admins for partners within their scope
- Adds some user policy tests to assert the scope is behaving as it should
> Hide untagged partner admins from partnership admins

- app/policies/user_policy.rb
- test/policies/user_policy_test.rb
Fixes #2169 
Fixes #2212
Adds in a missing part of the puzzle - allowing partner admins to also see all the users that admin for their partners, and in a way that works in conjunction with other admin types, so for example, if you're a neighbourhood admin for manchester and also a partner admin for a gardening group based in Liverpool, you can see every user that admins for a partner based in manchester as well as every user that admins for your gardening group.
> Add partner admins into scope

- app/controllers/admin/calendars_controller.rb
- app/policies/calendar_policy.rb
- test/factories/user.rb
- test/policies/calendar_policy_test.rb
fixes #2170 
- adjust scope to account for tags
- adjust edit policy to prevent partnership_admins accessing calendars directly via URL
> restrict partnership_admin access to calendars by neighbourhood AND partnership tag

- app/javascript/controllers/user_partners_controller.js
Fixes #2175 
## Description
Honestly I cannot believe that this just works! We managed to already design a controller for this that simply compares a list of permitted 'removable' users with the user being removed by the user, which very helpfully evaluates correctly who will disappear from your sight upon removal regardless of whether you are a partnership, neighbourhood, or partner admin. Wonderful!
So, to address the needs of this ticket, I went down a teeny rabbit hole to change the error message wording to reflect the role of each user, but on reflection decided it would be good to keep this very loosely coupled and made much more sense from a users' perspective to use generic language rather than couching the whole thing in current PlaceCal terminology, so I just rewrote it to work …
> improve error messages

- app/controllers/admin/partners_controller.rb
fixes #2224 
fixes #2229 
Another controller hook miss for the select2 stimulus controller.
> ensure correct select2 js controller is invoked on a new partner with a failed validation

- app/controllers/admin/users_controller.rb
- app/policies/user_policy.rb
- test/integration/admin/user_integration_test.rb
Fixes #2227
This changes the user policy so that only admin users with partners can create users. In our current system the relationship between one user and another hinges entirely on the partners they can see, so if you can't see any partners, you can't see any users, and should not be able to create them.
I've also updated the user create form so that any admin user other than a root who can create a user is now forced to attach a partner to them in the process - this will prevent partner admins from being able to create rogue users, and simplifies the logic here.
> Prevent user creation without partners

- config/application.rb
> Use rails 7 cache format from now on

- Gemfile
- Gemfile.lock
- app/controllers/joins_controller.rb
- app/views/joins/new.html.erb
Fixes #2265 
- adds invisible captcha gem and implements in the get in touch form
- this gem should prevent us from receiving excess unwanted spam. It does a few things to try to prevent this, the main ones being it prevents very fast responses & any responses that come in through the hidden field.
- I've tested this and it works great locally - human responses coming through fine, but if you input into the hidden field nothing happens.
> Add invisible captcha gem

- app/controllers/admin/partners_controller.rb
- app/mailers/moderation_mailer.rb
- app/views/admin/partners/_form.html.erb
- app/views/moderation_mailer/hidden_message.html.erb
- app/views/moderation_mailer/hidden_staff_alert.html.erb
## Description
- Small edits to the email & UI info that is shown to partner admins if their partner is hidden to remove the details of the user who moderated them. Now they will have to email support@placecal.org to settle any problems that arise.
- Change to the email sent to support@placecal.org as a notification that this action has been taken to include the information about who took the action.
> Update the way partner moderation works to remove the sharing of emails

- app/views/admin/partners/_form.html.erb
- test/integration/admin/partner_integration_test.rb
fixes #2310 
I've moved the place based parts of the form together and added text explaining that one is required. Updated with honor's description for people using the admin UI. Hopefully this makes it a bit clearer.
> make place requirements clearer on partner forms

- app/components/hero_section_component/hero_section_component.html.erb
fixes #2329 
check if image is there before adding image element.
> handle optional hero image

- Gemfile.lock
Closes #2367
Bit of a rabbit hole this one: when visiting unknown routes like `/foofoofoo` or `/styleguide/styleguide/event` the server would 500 with no backtrace (probably because there was an error in the error handler). 
Turns out the rollbar gem (v3.3.0) likely had a bug in it that is fixed in the latest version (v3.5.2)
> Updated rollbar gem

- app/views/admin/calendars/show.html.erb
- test/controllers/admin/calendars_controller_test.rb
Closes #2328 
When a calendar has notices and an admin visits the "show calendar" page, those notices are displayed like how they show on the "edit calendar" page.
> Fix of admin show calendar page with notices

- app/views/sites/default.html.erb
- test/integration/sites_integration_test.rb
fixes #2384
I think the reason it looks like so much text is because previously the large hero text was such poor contrast it was getting ignored. I've just pulled the hard-coded boilerplate below the hero text and removed the reference to places that duplicates local orgs.
> reduce instance homepage boiler plate text

- app/views/admin/partners/_address_fields.html.erb
- test/integration/admin/partner_integration_test.rb
fixes #2310 
- text approved from previous pr  #2317 
- removed required status from 1st line of address and postcode field
If someone misses out both these fields when adding the address, and they have a service area, it fails silently (refreshing the page but no warning). An unlikely event but it does not allow the creation of a malformed address.
There is a related issue #2364 that is outside the scope of the PR
> Address fields are not required on the partner form

- app/views/layouts/admin/_admin_navigation.html.erb
fixes #2146 
Added all the suggested links into the sidebar and moved the report a bug link in there too, I wrote the AC as appearing for admins but I included roots in this too as there seemed no harm in it and being familiar with what other users will see will make it easier to advice / support people.
> add support section to sidebar in admin ui

- .rubocop.yml
- app/jobs/calendar_importer/event_resolver.rb
- app/models/address.rb
- app/models/partner.rb
- test/jobs/calendar_importer/event_resolver_strategy_test.rb
- test/jobs/calendar_importer/events_import_test.rb
- test/support/geocoder.rb
Fixes #2348 
The event resolver has two strategies that can link up an event to a partner that is different to the partner they belong to.
These strategies previously tried to:
A) match with a partner by checking if the name and postcode in the event matched any partners in our DB
if this was unsuccessful they then tried to:
B) match with a partner by checking if the address matched any partners' addresses in our DB
if this was unsuccessful they then tried to:
C) create a new address from the event
Route B was broken - it would return true if just the first line of the address matched. 
I've decided to simply remove this option because I think it's poorly thought out - in our system it could be possible for multiple partners to exist at the same address and this only returns one. However …
> Prevent events from linking up to the wrong partner

- app/controllers/admin/calendars_controller.rb
- app/models/calendar.rb
- test/models/calendar_state_test.rb
Fixes #2304 
After a bit of digging it seemed like the easiest solution here was to improve the notification shown in the header and to also immediately import a calendar's events on creation. That means that the user doesn't get to specify the date to import from on their first import (it will just default to now) but they can change that at any point after the import, and changing it to a date in the future will remove any events that have already been imported if they didn't want current events showing for any reason. We could add a field in the form to let them control when the import begins from on their first import, but that just felt like another thing for users to have to think about at the create stage when most of them probably don't really care about this, so I think this …
> Queue new calendars for immediate import

- app/graphql/types/event_type.rb
- app/graphql/types/query_type.rb
- app/models/partner.rb
Closes #2220 
Can a partner be viewed through an event even if not visible?
> Hiding partners from the GraphQL API that are set to `hidden`

- app/models/partner.rb
fixes #2391 
We basically had two ways of intercepting the validation and both were covering half the use cases but not working in unison which was quite confusing. Now we always validate address creation from a partner but we never attempt to create an address if all the fields are blank.
This means we don't get silent failure if someone puts the first line of their address in line two by mistake, we get warnings at the top of the page and highlighted fields that need attention and we retain user input even if it's bad.
>  handle failing partner address gracefully

- README.md
Fixes #2088 
Slims down the readme to include only the essentials:
- dependencies
- getting set up as a staff member
- troubleshooting (this is to highlight the fixes for issues we encountered during a fresh install)
- getting set up if you're not a staff member (with a caveat at the start that this is currently broken)
- testing, formatting, linting info
- the component generator (decided to leave this in as it is not obvious when developing)
> Readme updates to support ongoing development

- .rubocop_todo.yml
- app/components/event/_event.html.erb
- app/components/event/event_component.rb
- app/controllers/concerns/map_markers.rb
- app/controllers/events_controller.rb
- app/controllers/partners_controller.rb
- app/jobs/calendar_importer/calendar_importer_task.rb
- app/jobs/calendar_importer/event_resolver.rb
- app/models/event.rb
- app/models/partner.rb
- app/policies/partner_policy.rb
- app/views/admin/partners/_form.html.erb
- app/views/events/index_simple.html.erb
- app/views/shared/_events.text.erb
- db/migrate/20240411192949_add_can_be_assigned_events_to_partner.rb
- db/migrate/20240411200641_partner_can_be_assigned_events_set_value.rb
- db/schema.rb
- test/factories/neighbourhood.rb
- test/factories/partner.rb
- test/jobs/calendar_importer/calendar_importer_task_test.rb
- test/jobs/calendar_importer/event_resolver_strategy_test.rb
- test/jobs/calendar_importer/event_resolver_test.rb
- test/jobs/calendar_importer/events_import_test.rb
- test/models/partner_test.rb
Fixes #2381 
- Adds a field to partners 'can be assigned events' that enables users to decide whether or not their partner can be linked up to events imported from other calendars
- Events imported with a strategy that takes the address from an event no longer attach the event to partners whose address matches - they just give the event their own address
- In the front end, when an event's address is shown:
- if it was imported to display at the partner's location then that partner is shown OR
- if it matches the name and postcode of a partner who can be assigned events, then that partner is shown OR
- the event's own address is shown
- changes & adds some tests to assert the above is working as it should
> Partners control event connections

- app/jobs/calendar_importer/events/ics_event.rb
- test/jobs/calendar_importer/event_resolver_test.rb
Closes #2417 
When importing iCal feeds, detect any URL in the URL field and mark it as `indirect`
> Be more permissive about calendar event URLs

- .rubocop_todo.yml
- app/controllers/admin/calendars_controller.rb
- app/datatables/calendar_datatable.rb
- app/jobs/calendar_importer/calendar_importer_task.rb
- app/jobs/calendar_importer/parsers/base.rb
- app/jobs/calendar_importer/parsers/ics.rb
- app/models/calendar.rb
- app/views/admin/calendars/_form.html.erb
- app/views/admin/calendars/_importer_overview.html.erb
- app/views/admin/calendars/index.html.erb
- app/views/admin/sites/show.html.erb
- db/migrate/20240422091648_calendar_checksum_date.rb
- db/migrate/20240422092628_set_calendar_checksum_date.rb
- db/schema.rb
- test/controllers/admin/calendars_controller_test.rb
- test/factories/calendar.rb
- test/integration/admin/calendars_integration_test.rb
- test/jobs/calendar_importer/calendar_importer_task_test.rb
- test/models/calendar_state_test.rb
- test/models/calendar_test.rb
fixes #2373 
- added date of checksum to modal and record when we update.
- set this on all existing calendars to be the same as the import date as that's when the checksum would have been made before
- update the checksum as soon as we can / separate it out from the importer completion
- I thought I would need to stop it hashing a failed network request but the whole job stops running if that happens so no problem
-  remove request date from ical feeds, only effecting google but that makes up a very high percentage of our feeds.
- add a test to show importer / checksum increment independantly
- update ui to surface info
- I changed "events changed" to "importer ran" which differs from the AC but that date can be incremented even if the import finds no new events.
- I referenced "source …
> 2373 calendar last updated

- app/assets/stylesheets/base/grid.scss
- app/views/events/show.html.erb
Fixes #2426 
Adds another column to the event page, just to make it clear who the partner owner of an event is, ie who is the source of its calendar.
> Update event design to make organising partner clearer

- app/components/address/address_component.rb
- app/jobs/calendar_importer/events/ics_event.rb
Closes #2437 
If an event has a URL as its location field, make it in to an Online event. 
Also the location is still the URL (on the show event page) but now it is a link
> Handle events with URLs in 'location' field

- app/components/event_list/_event_list.html.erb
- app/controllers/events_controller.rb
- app/helpers/events_helper.rb
- config/routes.rb
fixes #2400 
Grabs the next future event, takes it's start date and links to it using the same logic as the paginator. Retains "period" mode and won't show if there's no future events.
https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/ee771365-b9b1-4eb0-bf2c-161958834802
> 2400 next eventful period

- app/components/event_list/_event_list.html.erb
Lil spacing /formatting issue: addressing this
> Tiny tweak to skip to next date copy

- Gemfile
- Gemfile.lock
- app/controllers/admin/partners_controller.rb
- app/helpers/partners_helper.rb
- app/javascript/controllers/partner_form_validation_controller.js
- app/javascript/controllers/partner_tags_controller.js
- app/models/partner.rb
- app/views/admin/partners/_form.html.erb
- app/views/admin/partners/_partnership_fields.html.erb
- app/views/admin/partners/new.html.erb
- test/models/partner_test.rb
- test/system/admin/partner_test.rb
- Added back in a gem that drops console into the error pages (unclear why this was removed)
- Did some refactoring to reduce duplicate code
- Fixed validation error
- Renamed methods to make clearer
- Create partner form now properly pre-populates
Fixes #2454
> Fix partner creation validations

- Gemfile
- Gemfile.lock
- app/models/address.rb
- app/models/calendar.rb
- app/models/partner.rb
- app/models/user.rb
This is causing a few issues:
- Partners can be created with dupe names but for a space
- Unnessecary validation messages are popping up for url fields with a whitespace before or after when we can just deal with this for people
- Addresss are outputting slightly strangely if they have spcaes at the end of lines
- Gem also does things like remove double spaces and stuff like that -- looks well thought out and zero depends
This is just a bit of a QoL tidyup improvement that will solve some of the issues we're seeing from live partners.
Second attempt at this, first one is [here](https://github.com/geeksforsocialchange/PlaceCal/pull/2457).
Fixes #2450 
Fixes #2452
> Strip whitespace before saving attributes

- app/controllers/events_controller.rb
I think this is a little high atm and feedback from organisers has been wanting to switch earlier.
At some point we can add in a feature to pick this manually but for now let's just knock it down a touch.
> fix: reduce event limit to switch to weekly view a touch

- app/views/partners/show.html.erb
Oversight in the conditional is resulting in the default og image, not the site one, showing up if the partner does not have an image set.
Fixes #2491
> Fix og:image on partners with no image set

- db/seeds/004_sites.rb
This change fixes an error that occurs when running bin/setup.
The Site seed referenced a domain attribute that's no longer part of the DB schema. It looks like domain was renamed to url in [this commit](https://github.com/geeksforsocialchange/PlaceCal/commit/888ef007da74d11cf5e3ec558cd35049752de58a), but this file wasn't updated to reflect that.
> fix: Change 'domain' attribute to 'url' in Site seed

- README.md
Fixes #2631
Adds a section describing the current contents of the code base
We are currently working to make the codebase more maintainable, so it makes sense to start with an audit of what's there now.
Future updates to the folder structure will need to remember to update this file.
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyODJmNTI3Y2M3NjgxYzYyM2JiMzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.iqc8OpKiraFAkuNlEqTu_gM5Mk13g4xFZ1PyIJiG9Fs">Huly&reg;: <b>PC-2629</b></a></sub>
> docs: Add documentation on repo folder structure

- Gemfile
- Gemfile.lock
- app/graphql/types/event_queries.rb
- app/helpers/events_helper.rb
- app/jobs/calendar_importer/events/linked_data_event.rb
- app/jobs/calendar_importer/parsers/ld_json.rb
- app/jobs/calendar_importer/parsers/manchester_uni.rb
- app/models/calendar.rb
- app/models/event.rb
- config/environments/test.rb
- config/initializers/application_controller_renderer.rb
- config/initializers/backtrace_silencers.rb
- config/initializers/content_security_policy.rb
- config/initializers/new_framework_defaults_6_0.rb
- test/integration/robots_integration_test.rb
- test/system/collections_test.rb
Updated rubocop gems and allowed it to autocorrect -- none of this is written by me!
Keeping gems updated and stop the dependabot branch spam
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI3ODQ2ODI3Y2M3NjgxYzYyNjNkM2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.qwCPeKdZPz8TKXPYvXfXV_UzWAO_KxIGS479wSAFg24">Huly&reg;: <b>PC-2641</b></a></sub>
> chore: Update rubocop and apply new cops

- app/views/collections/show.html.erb
No idea how this slipped through but this test failing. Note the whole collections system needs removing but this gets CI passing again.
```
Error:
CollectionsControllerTest#test_should_show_collection:
ActionView::Template::Error: The asset "2017/12/placecal_winter2017.pdf" is not present in the asset pipeline.
app/views/collections/show.html.erb:25
test/controllers/collections_controller_test.rb:12:in `block in <class:CollectionsControllerTest>'
663 tests, 1914 assertions, 0 failures, 1 errors, 0 skips
```
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU4YTNlZjFlMDYzMmRkMDhlMmMwNjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZ …
> fix: Remove ref to deleted asset

- db/seeds/004_sites.rb
Resolves # 
Fixes a big bug in the seed scripts that means that no default site is created when rails db:seed is run on a fresh checkout
This makes the intial setup easier.
I forked the repo, pulled down a copy onto my machine and ran the `bin/setup` script as directed in the readme.  When I started the dev server I saw the message 'You have no site in your database, have you run `rails db:seed`?' which prompted me to check the postgres instance where I could see there wasn't any rows in the site table. I then tried to run the code from `db/seeds/004_sites.rb` in `rails console` and got a message about URLs beginning with https://.  I adjusted the url in the code and re-ran manually at which point it worked.
After that I have deleted the dev and test databases and re-ran `rails …
> Fix site seed

- Gemfile
- Gemfile.lock
Resolves # 
Add the `mutex_m` gem dependency to resolve this noisy warning
```
/usr/local/bundle/gems/spring-2.1.1/lib/spring/watcher/abstract.rb:3: warning: /usr/local/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the def
ault gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
Also please contact the author of spring-2.1.1 to request adding mutex_m into its gemspec.
```
This is required in order to improve developer experience, particularly for new developers. It makes runs of `./bin/setup` much cleaner
In a Docker image built with the following Dockerfile
```dockerfile
FROM ruby:3.3.6
WORKDIR /src
EXPOSE 3000
ENV MISE_DATA_DIR="/mise"
ENV MISE_CONFIG_DIR="/mise"
ENV …
```
> build: add mutex_m dependency to resolve warnings in console output
